name: CI OSX

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Install macOS Tools
      run: |
        brew update
        brew install ninja llvm
        
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: OSX-RELEASE

    - name: Merge x86_64 and arm64 discord_game_sdk
      run: lipo -create -output ./_RELEASE/discord_game_sdk.dylib ./discord_game_sdk/lib/aarch64/discord_game_sdk.dylib ./discord_game_sdk/lib/x86_64/discord_game_sdk.dylib

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSSVOH_HEADLESS_TESTS=1 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -GNinja
      env:
        CC: /usr/local/opt/llvm/bin/clang
        CXX: /usr/local/opt/llvm/bin/clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    

    - name: Copy artifacts and make app bundle
      run: |
        cd ./_RELEASE/
        mkdir -p ./Open\ Hexagon.app/Contents/Resources
        mkdir ./Open\ Hexagon.app/Contents/MacOS ./Open\ Hexagon.app/Contents/MacOS/Profiles ./Open\ Hexagon.app/Contents/MacOS/Replays
        cp ../build/SSVOpenHexagon ../build/OHWorkshopUploader Open\ Hexagon.app/Contents/MacOS
        cp -r ../build/_deps/sfml-src/extlibs/libs-osx/Frameworks Assets ConfigOverrides Packs Open\ Hexagon.app/Contents/MacOS
        cp config.json scores.json users.json discord_game_sdk.dylib libsdkencryptedappticket.dylib libsteam_api.dylib Open\ Hexagon.app/Contents/MacOS
        cp ../macos/launcher.sh Open\ Hexagon.app/Contents/MacOS
        cp ../macos/icon.icns Open\ Hexagon.app/Contents/Resources
        cp ../macos/Info.plist Open\ Hexagon.app/Contents/
        install_name_tool -add_rpath Frameworks Open\ Hexagon.app/Contents/MacOS/SSVOpenHexagon
        install_name_tool -add_rpath . Open\ Hexagon.app/Contents/MacOS/SSVOpenHexagon
        cd ..
        
    - name: Put build in Zip
      run: zip -r MACOS_APP_RELEASE.zip ./_RELEASE/Open\ Hexagon.app

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: OpenHexagon-OSX
        path: MACOS_APP_RELEASE.zip

    - name: Run tests
      run: |
        mkdir -p build/test
        cp _RELEASE/*.dylib build/test
        cp -R _RELEASE/Packs build/test
        ninja -C build check
